# Generated by Django 6.1.1 on 2026-09-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='chess', max_length=50, verbose_name='Тип игры')),
                ('invitation_type', models.CharField(choices=[('challenge', 'Вызов на дуэль'), ('friendly', 'Дружеская игра'), ('tournament', 'Турнирная партия')], default='friendly', max_length=20, verbose_name='Тип приглашения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='chess', max_length=50, verbose_name='Тип игры')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Активна'), ('paused', 'Отложена'), ('finished', 'Завершена'), ('archived', 'Архивирована')], default='waiting', max_length=20, verbose_name='Статус')),
                ('time_mode', models.CharField(choices=[('limited', 'С ограничением времени'), ('unlimited', 'Без ограничения времени')], default='unlimited', max_length=20, verbose_name='Режим времени')),
                ('metadata', models.JSONField(default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_black', to=settings.AUTH_USER_MODEL, verbose_name='Чёрные')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_white', to=settings.AUTH_USER_MODEL, verbose_name='Белые')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(default=1, verbose_name='Номер партии')),
                ('initial_fen', models.CharField(blank=True, max_length=200, verbose_name='Начальная позиция')),
                ('moves', models.JSONField(default=list, verbose_name='Ходы')),
                ('current_fen', models.CharField(blank=True, max_length=200, verbose_name='Текущая позиция')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Активна'), ('paused', 'Отложена'), ('checkmate', 'Мат'), ('stalemate', 'Пат'), ('draw', 'Ничья'), ('resigned', 'Сдача'), ('timeout', 'Просрочка времени'), ('abandoned', 'Прервана'), ('finished', 'Завершена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('result', models.CharField(choices=[('white_win', 'Победа белых'), ('black_win', 'Победа чёрных'), ('draw', 'Ничья'), ('undefined', 'Не определён')], default='undefined', max_length=20, verbose_name='Результат')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_paused', models.BooleanField(default=False, verbose_name='Отложена')),
                ('metadata', models.JSONField(default=dict, verbose_name='Метаданные')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-started_at'],
            },
        ),
    ]
