# Generated by Django 6.1.1 on 2026-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='color_preference',
            field=models.CharField(default='random', max_length=10, verbose_name='Предпочтение цвета'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='time_control',
            field=models.CharField(default='unlimited', max_length=20, verbose_name='Контроль времени'),
        ),
    ]
