# Generated by Django 6.1.1 on 2026-10-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_invitation_color_preference_invitation_time_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='games.room', verbose_name='Комната'),
        ),
    ]
